### PR TITLE
Changes `.js.es6` to `.es6` extension

### PR DESCRIPTION
**Pull request by duggiefresh**
- Generates correct `.es6` extensions
- Tests have been updated as necessary

### CODE REVIEW

**Comment by rwjblue** [comment]
:heart: :+1:

**Comment by bcardarella** [comment]
Can you check the README to make sure it reflects this? Also, the README should have a note about aliasing the syntax highlighting in the user's editor. Lastly update the CHANGELOG

**Comment by duggiefresh** [comment]
Sounds good. Thanks.

**Comment by twokul** [comment]
@duggiefresh :+1:

**Pull request merged**
