### PR TITLE
Add comment with location history option. (ref #120)

### PR DESCRIPTION
**Pull request by abuiles**

### CODE REVIEW

**Comment by stefanpenner** [comment]
don't you set location on the router not a route?

**Comment by abuiles** [comment]
@stefanpenner oh you are right!

**Comment by abuiles** [comment]
@stefanpenner fixed :).

**Comment by rwjblue** [comment]
@abuiles - I'm not sure that we want to have a bunch of extra comments in the generated files. 

I think we should likely just make `history` the default and "Just Work".

**Comment by rwjblue** [comment]
@bcardarella - Thoughts?

**Comment by abuiles** [comment]
@rwjblue (oh right @rjackson) I'm cool with that, actually is a good way to start pushing forward history location. I think @bcardarella was thinking on #120 commented initially, but I will +1 on default

**Comment by rwjblue** [comment]
@abuiles - Sorry, I didn't see #120. I'm good with this either way, just would love to push history as the default.

**Comment by abuiles** [comment]
@rjackson no problem! I agree with history as default too. Did you see my comments on the greedy routes matcher? Any thoughts there?

**Comment by bcardarella** [comment]
I actually have a local branch that I'm working on this. I want to have it as a single commit to address #120 where the comment in both the Ember router and the greedy routes matcher in the Rails routes.rb file. I'm OK with pulling this in but I'll probably overwrite with my commit this weekend.

**Comment by abuiles** [comment]
@bcardarella oh go ahead with yours :), looking forward for that.

**Comment by bcardarella** [comment]
For reference I just pushed it to #126

**Comment by abuiles** [comment]
@bcardarella btw, how does your greedy matcher look like?

**Comment by bcardarella** [comment]
We've been using this:

``` ruby
get '*foo', :to => 'landing#index'
```

And we put it as the very last route declaration in `config/routes.rb`

**Comment by abuiles** [comment]
@bcardarella thanks! yeah that's better than have greedy matchers per-resource.

**Comment by eccegordo** [comment]
What is the process to create a non ember route in the project? 
E.g. a page that is just vanilla rails view that doesn't load ember?

Is there a convenient way to override the default behavior through configuration?

I am wondering how feasible it is do something like
`<%= javascript_include_tag "ember_app" %>`
And only load it on select views instead having ember load for every single page.

Since this project does a lot of customization of the way the asset pipeline functions, does it make any sense to add a configuration option to not load ember in select cases?

If I create a 

`config/ember_app.js`

That looks something like this

```
//= require jquery
//= require environment
//= require ember-appkit
//= require_self
//= require adapter
//= require router
//= require_tree ../app
//= require_tree ./initializers

window.App = require('app').default.create();
```

and leave `config/application.js` blank

Will I run into any unintended side effects because of the way the rest of eak-rails is setup?

Any gotchas?

**Comment by eccegordo** [comment]
I would presume that one consequence is that if you navigate away from ember based pages you would lose all the intermediary state of the loaded up ember app including what might be cached in the store. And would need to reload everything when you navigate back. So have to be careful about some edge cases.

**Comment by bcardarella** [comment]
Because the Rails router is a "first win" from the top down you just put your non-ember route above the greedy matcher. Then you would have to create a new layout view that doesn't include `application`

**Comment by abuiles** [comment]
@bcardarella @eccegordo I started this https://github.com/dockyard/ember-appkit-rails/wiki/FAQ so we keep track of this kind of questions.

**Comment by abuiles** [comment]
Also a simple home for the wiki https://github.com/dockyard/ember-appkit-rails/wiki

**Pull request closed without merging**
