### PR TITLE
Closes #87

### PR DESCRIPTION
**Pull request by acacheung**

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like [this](https://github.com/dockyard/ember-appkit-rails/blob/master/test/integration/navigation_test.rb#L8) is failing because that exact text doesn't appear anymore.

@acacheung - Could you update the PR to look for some text that is on the new landing page?

**Comment by bcardarella** [comment]
I just need to change to: "That was easy, wasn&rsquo;t it?"

**Comment by rwjblue** [comment]
@bcardarella - Yep, makes sense. Was just pointing out where the failure was coming from. 

Also, this is awesome!

**Comment by rwjblue** [comment]
The integration test was updated in 863c4a4.

**Comment by bcardarella** [comment]
We can follow up later with changing the image.

**Pull request merged**
