### PR TITLE
Ensure config/serializers is picked up by Sprockets.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by bcardarella** [comment]
Is this going to turn into one of those never ending battles of just adding more and more directories to this file? I'm OK with serializers and transforms as well but we should look into maybe having something automatic instead. Basically any directory should be `require_tree`'d except for disallowed ones like `environments` and `initializers` Thoughts?

**Comment by rwjblue** [comment]
@bcardarella - I agree. We should use a custom directive that requires all of these directories automatically. This should apply to `app/` and `config/` and use a blacklist to allow folks to opt-out for specific patterns. 

Also just to clarify, we do need `config/environments/` and `config/initializers` to be served also.

**Comment by bcardarella** [comment]
I'm guessing the build failed because the directory doesn't exist

**Comment by bcardarella** [comment]
@rjackson `initializers` yes, but `environments` is not using `require_tree` because it is loading only a special file depending upon the Rails environment.

**Comment by eccegordo** [comment]
Does it make sense to add some sort of preflight or post flight check script/task that can alert a user of existing project what is missing if they upgrade and the appkit project structure changes or expected folders are missing?

Programmatically handling the required structure makes sense but also wondering about the case where a user accidentally removes stuff and breaks their project.

This might be obscure to novice users who know nothing of the resolver etc. Some sensible sanity check that informs the user might be wise.

**Comment by rwjblue** [comment]
@bcardarella - You are correct, this definitely failed due to the missing folder. Fixed now.

**Comment by bcardarella** [comment]
@eccegordo as the README states the library is still pre-1.0 and there will be breaking changes between versions. Over the weekend I added a note for a strategy on upgrades.

**Pull request merged**
