### PR TITLE
Use respond_with and respond_to.

### PR DESCRIPTION
**Pull request by abuiles**

### CODE REVIEW

**Comment by bcardarella** [comment]
damn it, I keep forgetting to ask people to update the CHANGELOG

**Comment by abuiles** [comment]
haha will do now!

**Comment by bcardarella** [comment]
I already added

**Comment by abuiles** [comment]
Noticed it, btw, shouldn't this
https://github.com/dockyard/ember-appkit-rails/pull/118/files#diff-419ab95b9e62ba7f0baacdb401345059R2be
in the Changelog too?

**Comment by bcardarella** [comment]
eh, that was more of a "get it out the door" for 0.3.0 at the end. I pulled an all-nighter and it was the one last thing :)

**Pull request merged**
