### PR TITLE
jj-abrams-resolver now lives under the module name ember/resolver

### PR DESCRIPTION
**Pull request by jayphelps**
per stefanpenner/ember-jj-abrams-resolver#27

Note: This also pulls in some changes to the resolver itself, want me to slice this into two commits?

### CODE REVIEW

**Comment by bcardarella** [comment]
@jayphelps can you update the CHANGELOG?

**Comment by jayphelps** [comment]
@bcardarella Sure, what's the convention? Does this require a minor version bump?

**Comment by rwjblue** [comment]
@jayphelps We haven't released 0.5.0, so just stuck it under that header.

**Comment by jayphelps** [comment]
@rjackson @bcardarella perf.

**Comment by jayphelps** [comment]
@bcardarella @rjackson 
party

**Comment by bcardarella** [comment]
:sunglasses:

**Pull request merged**
