### PR TITLE
Ember-app-kit like adapters

### PR DESCRIPTION
**Pull request by wouterw**
Replaces `store.js` with `adapters/application.js.es6` as seen in http://github.com/stefanpenner/ember-app-kit.

### CODE REVIEW

**Comment by bcardarella** [comment]
@stefanpenner under what circumstances would you ever want more than one adapter running?

**Comment by stefanpenner** [comment]
@bcardarella multiple backends?

**Comment by rwjblue** [comment]
It seems to be an edge case sort of thing to me.  It is fairly easy to roll your own if you need the more advanced setup, but I'm not sure we need another top level dir for it by default (likely >90% of folks will use the current defaults)...

**Comment by bcardarella** [comment]
Yeah, considering this is intended for Rails only I'm not sure multiple backend support is necessary for a default. Although I do like the "adapter" more than "store". @wouterw would you be willing to modify the PR to just rename "store.js.es6" to "adapter.js.es6" ?

**Comment by wouterw** [comment]
I think multiple adapters are useful during early development and prototyping of the UI.
I'm currently working on a project where the API is still in an early stage. The `FixtureAdapter` is very useful here to build out parts of the UI independently.

I do agree on the >90% rule, as it's easy to setup. I'll go ahead and rename `store.js.es6` to `adapter.js.es6`.

**Comment by bcardarella** [comment]
@wouterw that is a very good point about the FixtureAdapter. We haven't really made much use of it so I didn't give it much consideration. Why don't we go with the file rename. We are still well below a 1.0 release of the library. Let's get some people using it, see if this causes too much friction. If it ends up being a default that a lot of people change or if they are putting two adapters into the adapters.js.es6 file we'll go with the adapters directory setup

**Comment by bcardarella** [comment]
@wouterw can you rebase and squash so I can merge?

**Comment by wouterw** [comment]
@bcardarella I've rebased, reverted my changes and did the renaming.

**Comment by bcardarella** [comment]
thank you!

**Pull request merged**
