### PR TITLE
Update to latest resolver, remove Resolver monkey patches.

### PR DESCRIPTION
**Pull request by rwjblue**

### CODE REVIEW

**Comment by stefanpenner** [comment]
+1

**Comment by bcardarella** [comment]
@rjackson doesn't this need to have some configuration set in `config/environment.js` ?

**Comment by rwjblue** [comment]
The changes needed were already made (in https://github.com/dockyard/ember-appkit-rails/pull/150).

**Comment by bcardarella** [comment]
:+1:

**Pull request merged**
