### PR TITLE
Make environment js files erb to enable reading values from ENV.

### PR DESCRIPTION
**Pull request by statik**
As discussed tonight at the Ember.js for Rails Devs workshop at Dockyard offices:
Reading config values from environment instead of hardcoding keys in your JS files is a best practice and important for environments like heroku (also possible with on non-heroku environments using the Figaro gem). In order to do this, the environment js files need to be .erb.

Not sure if the example I placed in production.js.erb is sufficient.

### CODE REVIEW

**Comment by rwjblue** [comment]
@statik - Can you fixup the tests (they are assuming that the files are named `.js` not `.js.erb`)?  Could you also add an instructive comment (in prose) above the example you provided?

**Comment by bcardarella** [comment]
@statik your other PR also changed `CHANGELOG.md`. Can you rebase this against master so I can merge?

**Comment by statik** [comment]
@bcardarella Sure thing, rebased and squashed.

**Comment by bcardarella** [comment]
@statik thank you

**Pull request merged**
