### PR TITLE
Add Gemfile.lock to .gitignore

### PR DESCRIPTION
**Pull request by duggiefresh**
- Removes Gemfile.lock

### CODE REVIEW

**Comment by mehulkar** [comment]
Just out of curiosity, why is Gemfile.lock ignored? Is this good practice for full Rails apps as well?

**Comment by rwjblue** [comment]
@mehulkar - Generally speaking reusable libraries (which EAKR is) should not have a Gemfile.lock, whereas applications (where you control the whole stack) would.

**Comment by duggiefresh** [comment]
@mehulkar Please see http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

Yehuda clears a lot up between `Gemfile.lock` and `gemspecs`.

**Comment by mehulkar** [comment]
@duggiefresh thanks for that link!

**Pull request merged**
