### PR TITLE
ember:bootstrap creates directory structure for custom --app-paths

### PR DESCRIPTION
**Pull request by sbl**
The generator was not creating the models, controllers, views directories for a custom app-path.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks good. We were not creating directories that would have existed already in the default path when using a path other than `app/`.

@sbl - Could you add an entry to the CHANGELOG for this?

**Comment by bcardarella** [comment]
:+1: once CHANGELOG is updated

**Comment by sbl** [comment]
I already updated the changelog. If you prefer I can squash this later.

**Comment by bcardarella** [comment]
Nah, this is cool. Thanks!

**Pull request merged**
