### PR TITLE
Add Bundler caching to Travis

### PR DESCRIPTION
**Pull request by duggiefresh**
[ci skip]

### CODE REVIEW

**Comment by rwjblue** [comment]
Unless they have changed it, this only works on private repos.

**Comment by rwjblue** [comment]
From http://docs.travis-ci.com/user/caching/ :

> The features described here are currently only available for private repositories on travis-ci.com.

**Comment by duggiefresh** [comment]
Ah good to know. Thanks!

**Comment by rwjblue** [comment]
In Ember we use a custom script that uploads the bundle to S3 for us.  See [here](https://github.com/emberjs/ember.js/blob/master/bin/cached-bundle).

**Pull request closed without merging**
