### PR TITLE
It's Ember App Kit.

### PR DESCRIPTION
**Pull request by abuiles**
The `Appkit` might be intentional, if not it should be separated.

### CODE REVIEW

**Comment by bcardarella** [comment]
It is intentional

On Friday, January 31, 2014, Adolfo Builes notifications@github.com wrote:

> ## The Appkit might be intentional, if not it should be separated.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/abuiles/ember-appkit-rails spelling
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/dockyard/ember-appkit-rails/pull/180
> Commit Summary
> - It's Ember App Kit.
> 
> File Changes
> - _M_ README.mdhttps://github.com/dockyard/ember-appkit-rails/pull/180/files#diff-0(20)
> 
> Patch Links:
> - https://github.com/dockyard/ember-appkit-rails/pull/180.patch
> - https://github.com/dockyard/ember-appkit-rails/pull/180.diff
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dockyard/ember-appkit-rails/pull/180
> .

## 

---

Brian Cardarella
CEO of DockYard
Visit us: http://dockyard.com
Call us: (855) DOCK-YRD
Follow me on Twitter: http://twitter.com/bcardarella
Follow us on Twitter: http://twitter.com/DockYard

**Comment by abuiles** [comment]
@bcardarella cool, I was jut writing about it and `Ember Appkit Rails` looked weird to me. But that's just me :).

**Comment by bcardarella** [comment]
Moar detail: its only intentional because the convention in ruby land of dasherizing word separations and underscoring camelcase. So if I were to write it out properly it would be: `ember-app_kit-rails` which looks fugly. If we did `ember-app-kit-rails` similar to the original library Bundler would expect a load path of `ember/app/kit/rails` which seems like unnecessary namespacing. Finally, in ruby land the dashes for a gem name usually denote a context. I consider the name to mean:
- `ember`: this is an ember-related library similar to `ember-source`
- `appkit`: this is actually an implementation of App Kit
- `rails`: for Rails

**Comment by rwjblue** [comment]
Thank you for jotting this down. I'm sure we will have this question come up from time to time, and this is a great explanation to link to.

**Comment by abuiles** [comment]
@bcardarella @rjackson F.A.Q :+1:  thanks for the explanation Brian.

**Comment by bcardarella** [comment]
I've got reasons! :smiley:

**Pull request closed without merging**
