### PR TITLE
Fix typo in adapter template.

### PR DESCRIPTION
**Pull request by rwjblue**
We likely should roll 0.4.1 with this update, and possibly #156.

### CODE REVIEW

**Comment by bcardarella** [comment]
This is incorrect. We want the template to spit out erb. The `%%` means that it won't evaluate the erb and will instead spit out a single `%` erb statement.

**Comment by rwjblue** [comment]
OK, that makes sense. If we are not intending to interpret the  ERB why not just use the `copy_file` Thor action (instead of `template` which evaluates the ERB)?

**Comment by bcardarella** [comment]
That would be better. I think there is another issue, the adapter should go into config/adapters/application.js.es6.erb

**Comment by rwjblue** [comment]
OK, will PR

**Pull request closed without merging**
