### PR TITLE
Mentions that you have to remove turbolinks

### PR DESCRIPTION
**Pull request by twokul**
#30

### CODE REVIEW

**Comment by bcardarella** [comment]
I am wondering if the bootstrap generator should attempt to cleanse the app of turbolinks all together. Also `jquery-ujs` should be unnecessary.

We should be able to do this pretty easily with the generator and some of the Thor directives

**Comment by rwjblue** [comment]
I believe that we should likely offer a template to install from (ember-rails has one in the root of the ember website).

**Comment by twokul** [comment]
Seems like we need to create a separate issue

**Comment by bcardarella** [comment]
are people using that? I would prefer the default of the bootstrap generator to put the rails app in the best situation possible for a working ember application with a single command

**Comment by rwjblue** [comment]
Yeah, that makes sense. I do think that we should offer a template to make getting a new app going a bit faster, but our generator should definitely remove turbo links either way.

**Comment by twokul** [comment]
I gotta read about Thor directives. Right now, it sounds Greek to me

**Comment by rwjblue** [comment]
Added removal of `turbolinks` automatically in: https://github.com/dockyard/ember-appkit-rails/pull/43.

**Comment by rwjblue** [comment]
@twokul - Should we close this in favor of #43?

**Comment by bcardarella** [comment]
Yes, closing in favor of #43

**Pull request closed without merging**
