### PR TITLE
Ember Data adapters will resolve under config prefix

### PR DESCRIPTION
**Pull request by bcardarella**
Breaking commit for pending PR

### CODE REVIEW

**Comment by rwjblue** [comment]
There is a rake task that updates the resolver to the latest version. We need to determine how to support that if we are going to monkey patch.

**Comment by bcardarella** [comment]
@rjackson that rake task should be removed as the `resolveRouter` function was modified from default Ember App Kit's resolver a while back.

**Comment by bcardarella** [comment]
@rjackson unless we can reopen the Resolver after resolver.js is run then do the modifications. This way the original EAK resolver stays intact and the rake task should be OK.

**Comment by rwjblue** [comment]
To me this means that we are not exercising the resolver enough in our tests. If we have to monkey patch I would prefer to do it in a separate file so that we can still take advantage of changes/fixes in the upstream resolver.

**Comment by bcardarella** [comment]
@rjackson I agree, I'll make those changes later tonight. Original resolver will stay intact and we'll monkey patch in another file

**Pull request merged**
